FROM node:22.13.1  AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN node ace build

FROM node:22.13.1  AS production

WORKDIR /app

COPY --from=build /app/build ./build

WORKDIR /app/build

RUN npm ci --omit=dev

EXPOSE 3000

CMD ["node", "bin/server.js"]
